
services:
  nestar-next:
    container_name: bookio-next
    restart: always
    image: node:20.10.0
    ports:
      - 5000:4000
    environment:
     - PORT=4000

    volumes:
      - ./:/usr/src/bookio-next
    working_dir: /usr/src/bookio-next

    networks:
      - client-network
    
    #FOR PRODUCTION
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge